version: "3"

services:
  bot:
    build:
      context: "."
    volumes:
      - "./:/root/bukibot"
    command: python main.py
    ports:
      - "5000:5000"
    environment:
      LINE_CHANNEL_SECRET: $LINE_CHANNEL_SECRET
      LINE_CHANNEL_ACCESS_TOKEN: $LINE_CHANNEL_ACCESS_TOKEN
